# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_authtoken_category_feedback_infoobject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.SlugField(allow_unicode=True),
        ),
    ]
